### PR TITLE
bump core to absorb libp2p #393

### PR DESCRIPTION
**Pull request by lthiery**

### CODE REVIEW

**Comment by madninja** [comment]
Ideally you would bump core by explicitly stating the ref in rebar.config instead of hacking lock files

**Comment by lthiery** [comment]
> Ideally you would bump core by explicitly stating the ref in rebar.config instead of hacking lock files

I was told `./rebar3 upgrade blockchain` was the way? I tried explicit tagging in `rebar.config` previously but apparently we're not doing that here.

@macpie @michaeldjeffrey are we still happy with this standard?

**Comment by madninja** [comment]
> > Ideally you would bump core by explicitly stating the ref in rebar.config instead of hacking lock files
> 
> I was told `./rebar3 upgrade blockchain` was the way? I tried explicit tagging in `rebar.config` previously but apparently we're not doing that here.
> 
> @macpie @michaeldjeffrey are we still happy with this standard?

huh odd.. so we're not using `{ref, "git sha"}` for untagged core upgrades in rebar.config but hacking the lock file? That's.. not very clean?

**Comment by lthiery** [comment]
> huh odd.. so we're not using `{ref, "git sha"}` for untagged core upgrades in rebar.config but hacking the lock file? That's.. not very clean?

Well, TBF, I don't find `./rebar3 upgrade xx` to be "hacking the lock file" since it's done programatically at least. But, yea I prefer the standard of explicit tags in the `rebar.config` as well. It's just not been the practice in router and packet-purchaser afaik

**Pull request closed without merging**
